
DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: deepextremes
    StoreId: s3
    StoreParams:
      root: deepextremes
      storage_options:
        anon: True
    Datasets:
      - Path: "*.zarr"
